# ==============================================================================
# 🛡️ GitPR - Local Static Linter Configuration
# ==============================================================================
# This file defines the quality rules that run on the developer's machine.
# GitPR analyzes only the MODIFIED LINES in the 'git diff'.
#
# Rule Properties:
# - name: Unique rule identifier (no spaces).
# - level: 'error' (blocks the commit) or 'warning' (displays a yellow alert only).
# - extensions: List of file extensions where the rule applies (e.g.: ["php", "js"]).
# - require_paths: (Optional) Limits execution to specific folders (e.g.: ["routes/*"]).
# - ignore_paths: (Optional) Ignores specific folders (e.g.: ["vendor/*", "tests/*"]).
# - regex: The search regular expression (ALWAYS use single quotes '').
# - message: The alert text. Accepts the variables {file_name} and {line_number}.
# - ignore_comments: true (ignores commented code) / false (reads comments).
# ==============================================================================

rules:
  # ---------------------------------------------------------
  # 🚨 CRITICAL ERRORS (Block the Commit)
  # ---------------------------------------------------------

  #- name: ""
  #  level: ""
  #  extensions: [""]
  #  regex: ''
  #  message: ""
  #  ignore_comments: true

  # ---------------------------------------------------------
  # ⚠️ BEST PRACTICE WARNINGS (Do not block the Commit)
  # ---------------------------------------------------------



  - name: "warning-todo-fixme"
    level: "warning"
    extensions: ["php", "js", "ts", "vue", "py"]
    regex: '(?i)(TODO|FIXME):'
    message: "⚠️ Warning: There is a pending TODO or FIXME annotation in {file_name} (Line {line_number})."
    ignore_comments: false # Here we intentionally need to read the comments!

  - name: "check-ia-indice"
    extensions: ["py"]
    level: "warning"
    regex: '^\s*#\s*\d+\.'
    message: "🚨 Index comment found in file {file_name} (Line {line_number}) - Check if intentional or AI-generated"
    ignore_comments: false
